### ISSUE TITLE
Extra data directory in wallabag unraid template

### ISSUE THREAD

**Issue by davidb7** [Code-Slave/unraid-dockers#1]
I was able to get wallabag running on my unRaid server following this template, but I had to remove one of the 2 data directories in "/var/www/wallabag/data/data" to get everything mapped correctly.

Thank you for this, by the way. I've been wanting to run wallabag for a while now, but hadn't been able to get it to work.

**Comment by Code-Slave** [comment]
np at all. thanks for the heads up ill change it if you let me know exactly how it changed
